version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - worker
      - beat
      - flower
    networks:
      - django_network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery worker --pool=solo -l info
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - django_network

  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery beat -l info
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - django_network

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app flower --address=0.0.0.0 --port=5555 --persistent=True --db=flower.db5
    env_file:
      - .env
    ports:
      - '5555:5555'
    depends_on:
      - redis
    networks:
      - django_network

  redis:
    image: redis
    networks:
      - django_network

  db:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - django_network

networks:
  django_network:
    external: true
    driver: bridge