version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - worker
      - beat
      - flower
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery worker --pool=solo -l info
    env_file:
      - .env
    depends_on:
      - redis
  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.celery beat -l info
    env_file:
      - .env
    depends_on:
      - redis
  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app flower --address=0.0.0.0 --port=5555 --persistent=True --db=flower.db5
    env_file:
      - .env
    ports:
      - '5555:5555'
    depends_on:
      - redis
  redis:
    image: redis
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
