# Generated by Django 4.2.2 on 2023-07-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('cc', models.CharField(blank=True, max_length=1000)),
                ('attachment', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='storedemail',
            name='attachment',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
