# Generated by Django 4.2.2 on 2023-07-26 10:31

from django.db import migrations, models
import send_mail.models


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0002_sentmail_alter_storedemail_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to=send_mail.models.upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
