# Generated by Django 4.2.2 on 2023-07-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send_mail', '0003_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='name',
            new_name='filename',
        ),
    ]
